//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace SpryCoder.Camever.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string CameraHostname {
            get {
                return ((string)(this["CameraHostname"]));
            }
            set {
                this["CameraHostname"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("cgi-bin/snapshot.cgi")]
        public string SnapshotUrl {
            get {
                return ((string)(this["SnapshotUrl"]));
            }
            set {
                this["SnapshotUrl"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("15")]
        public string UpdateInterval {
            get {
                return ((string)(this["UpdateInterval"]));
            }
            set {
                this["UpdateInterval"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string ImageSavePath {
            get {
                return ((string)(this["ImageSavePath"]));
            }
            set {
                this["ImageSavePath"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("{year4}{monthno}{day}-{24hour}{min}{sec}")]
        public string ImageFileNamingFormat {
            get {
                return ((string)(this["ImageFileNamingFormat"]));
            }
            set {
                this["ImageFileNamingFormat"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool CapturesEnabled {
            get {
                return ((bool)(this["CapturesEnabled"]));
            }
            set {
                this["CapturesEnabled"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string WundergroundCameraID {
            get {
                return ((string)(this["WundergroundCameraID"]));
            }
            set {
                this["WundergroundCameraID"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string WundergroundPassword {
            get {
                return ((string)(this["WundergroundPassword"]));
            }
            set {
                this["WundergroundPassword"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool WundergroundUploadEnabled {
            get {
                return ((bool)(this["WundergroundUploadEnabled"]));
            }
            set {
                this["WundergroundUploadEnabled"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool KeepOnTop {
            get {
                return ((bool)(this["KeepOnTop"]));
            }
            set {
                this["KeepOnTop"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("BottomRight")]
        public string WindowLocation {
            get {
                return ((string)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5")]
        public int OverlayTransparency {
            get {
                return ((int)(this["OverlayTransparency"]));
            }
            set {
                this["OverlayTransparency"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string OverlayTopLeftText {
            get {
                return ((string)(this["OverlayTopLeftText"]));
            }
            set {
                this["OverlayTopLeftText"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string OverlayTopRightText {
            get {
                return ((string)(this["OverlayTopRightText"]));
            }
            set {
                this["OverlayTopRightText"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string OverlayBottomLeftText {
            get {
                return ((string)(this["OverlayBottomLeftText"]));
            }
            set {
                this["OverlayBottomLeftText"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("{monthno}/{day}/{year4} {12hour}:{min}:{sec} {ampm}")]
        public string OverlayBottomRightText {
            get {
                return ((string)(this["OverlayBottomRightText"]));
            }
            set {
                this["OverlayBottomRightText"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Amcrest")]
        public string CameraMfg {
            get {
                return ((string)(this["CameraMfg"]));
            }
            set {
                this["CameraMfg"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string LaunchCode {
            get {
                return ((string)(this["LaunchCode"]));
            }
            set {
                this["LaunchCode"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
    }
}
